
# DataSource Config
spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: utf-8
  #面向切面开启
  aop:
      auto: true


  redis:
    host: localhost
    port: 6379
    timeout: 6000
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

server:
  port: 8083

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    #控制台打印输出完整的sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 系统输出日志
logging:
  config:
    classpath: log4j2.xml



